steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-central1-docker.pkg.dev/wally-registry-487222/wally/wally-backend:$COMMIT_SHA',
        '-f',
        'wally-registry-backend/Dockerfile',
        '.'
      ]

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/wally-registry-487222/wally/wally-backend:$COMMIT_SHA'
      ]

  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run',
        'deploy',
        'wally-backend',
        '--image',
        'us-central1-docker.pkg.dev/wally-registry-487222/wally/wally-backend:$COMMIT_SHA',
        '--region',
        'us-central1',
        '--platform',
        'managed',
        '--command',
        './launch',
        '--allow-unauthenticated'
      ]

timeout: 900s

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
